comment:
  layout: "reach, diff, flags"
  behavior: default
  require_changes: true

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
